/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.GUI;

import DAO.ExerciseDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import project.UserDetails.Exercise;
import project.UserDetails.User;

/**
 *
 * @author perfect solution
 */
public class ExerciseDetailsfrm extends javax.swing.JFrame {

    User user;
    Exercise exercise;

    /**
     * Creates new form ExercisesGUI
     */
    public ExerciseDetailsfrm() {
        initComponents();
        this.exercise = new Exercise();
        exercise.setName("Push ups");
        exercise.setProcedure("Begin in a plank position, with your hands directly under your shoulders, arms straight, and back flat. Lower your body until your chest nearly touches the floor. Push back up to the starting position. Repeat.");
        lblName.setText(exercise.getName());
        areaProcedure.setText(exercise.getProcedure());
        ImageIcon icon = new ImageIcon("src\\main\\resources\\images\\Sleep.jpg");
        lblImage.setIcon(ImageResizer.resize(icon, lblImage));
    }

    public ExerciseDetailsfrm(Exercise exercise,User user) {
        initComponents();
        this.exercise = exercise;
        lblName.setText(exercise.getName());
        areaProcedure.setText(exercise.getProcedure());
        ImageIcon icon = new ImageIcon("src\\main\\resources\\images\\" + exercise.getImage());
        lblImage.setIcon(ImageResizer.resize(icon, lblImage));
        
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaProcedure = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnRoutine = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setUndecorated(true);
        setResizable(false);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblName, org.openide.util.NbBundle.getMessage(ExerciseDetailsfrm.class, "ExerciseDetailsfrm.lblName.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ExerciseDetailsfrm.class, "ExerciseDetailsfrm.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblImage, org.openide.util.NbBundle.getMessage(ExerciseDetailsfrm.class, "ExerciseDetailsfrm.lblImage.text")); // NOI18N

        areaProcedure.setEditable(false);
        areaProcedure.setColumns(20);
        areaProcedure.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaProcedure.setLineWrap(true);
        areaProcedure.setRows(5);
        areaProcedure.setWrapStyleWord(true);
        jScrollPane3.setViewportView(areaProcedure);

        org.openide.awt.Mnemonics.setLocalizedText(btnAdd, org.openide.util.NbBundle.getMessage(ExerciseDetailsfrm.class, "ExerciseDetailsfrm.btnAdd.text")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnRoutine, org.openide.util.NbBundle.getMessage(ExerciseDetailsfrm.class, "ExerciseDetailsfrm.btnRoutine.text")); // NOI18N
        btnRoutine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoutineActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnBack, org.openide.util.NbBundle.getMessage(ExerciseDetailsfrm.class, "ExerciseDetailsfrm.btnBack.text")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                                .addComponent(btnRoutine)
                                .addGap(50, 50, 50))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBack)
                .addGap(91, 91, 91)
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoutine)
                    .addComponent(btnAdd))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JSpinner reps = new JSpinner(new SpinnerNumberModel(1, 1, 50, 1));
        JSpinner sets = new JSpinner(new SpinnerNumberModel(1, 1, 50, 1));
        Object[] message = {
            "Reps:", reps,
            "Sets:", sets
        };
        int option = JOptionPane.showConfirmDialog(null, message);
        if (option == JOptionPane.OK_OPTION) {
            exercise.setReps((Integer) reps.getModel().getValue());
            exercise.setSet((Integer) sets.getModel().getValue());
            ExerciseDAO.saveRoutine(user, exercise);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRoutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoutineActionPerformed
        // TODO add your handling code here:
        new Routinefrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRoutineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciseDetailsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciseDetailsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciseDetailsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseDetailsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciseDetailsfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaProcedure;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRoutine;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
