/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.GUI;

import DAO.NutritionDAO;
import DAO.SleepDAO;
import java.util.ArrayList;
import java.util.Calendar;
import project.UserDetails.Nutrition;
import project.UserDetails.Sleep;

import project.UserDetails.User;

/**
 *
 * @author perfect solution
 */
public class Homefrm extends javax.swing.JFrame {

    public User user;

    /**
     * Creates new form Homefrm
     */
    public Homefrm() {
        initComponents();
    }

    public Homefrm(User user) {
        initComponents();
        this.user = user;
        Calendar calendar = Calendar.getInstance();
        int hour = calendar.get(Calendar.HOUR_OF_DAY);

        String message;
        if (hour >= 0 && hour < 12) {
            message = "Good morning ";
        } else if (hour >= 12 && hour < 17) {
            message = "Good afternoon ";
        } else if (hour >= 17 && hour < 21) {
            message = "Good evening ";
        } else {
            message = "Good night ";
        }
        txtWelcomeMessage.setText(message + user.getName());
        ArrayList sleepData = SleepDAO.getSleepData(user);
        ArrayList nutritionData = NutritionDAO.getCalIntakeData(user);
        if (!sleepData.isEmpty()) {
            Sleep s = (Sleep) sleepData.get(sleepData.size() - 1);

            lblSleep.setText("Amount of sleep : " + s.getHours() + "Hours " + s.getMinutes() + "minutes");
        } else {
            lblSleep.setText("Amount of sleep : -");
        }

        if (!nutritionData.isEmpty()) {
            Nutrition n = (Nutrition) nutritionData.get(nutritionData.size() - 1);

            lblCalories.setText("Calories Intake: " + n.getCal() + " Calories");
        } else {
            lblCalories.setText("Calories Intake: -");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWelcomeMessage = new javax.swing.JLabel();
        lblSleep = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnMenuProfile = new javax.swing.JButton();
        btnMenuNutrition = new javax.swing.JButton();
        btnMenuExercise = new javax.swing.JButton();
        btnMenuSleep = new javax.swing.JButton();
        btnMenuHome = new javax.swing.JButton();
        lblCalories = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWelcomeMessage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        txtWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        txtWelcomeMessage.setText("Good Morning <Name>");
        getContentPane().add(txtWelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblSleep.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblSleep.setForeground(new java.awt.Color(255, 255, 255));
        lblSleep.setText("Hours of sleep :");
        getContentPane().add(lblSleep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 388, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 394, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Glasses of Water:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        btnMenuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-male-user-24.png"))); // NOI18N
        btnMenuProfile.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 90, 70));

        btnMenuNutrition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-vegetarian-food-24.png"))); // NOI18N
        btnMenuNutrition.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuNutrition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuNutritionActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuNutrition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 90, 70));

        btnMenuExercise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exercise-24.png"))); // NOI18N
        btnMenuExercise.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuExerciseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuExercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 90, 70));

        btnMenuSleep.setIcon(new javax.swing.ImageIcon("C:\\Users\\perfect solution\\Documents\\NetBeansProjects\\HealthFitness\\src\\main\\resources\\icons\\icons8-occupied-bed-24.png")); // NOI18N
        btnMenuSleep.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSleepActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuSleep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 90, 70));

        btnMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-page-32.png"))); // NOI18N
        getContentPane().add(btnMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 90, 80));

        lblCalories.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblCalories.setForeground(new java.awt.Color(255, 255, 255));
        lblCalories.setText("Calories Intake");
        getContentPane().add(lblCalories, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 340, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSleepActionPerformed
        // TODO add your handling code here:
        new Sleepfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuSleepActionPerformed

    private void btnMenuExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuExerciseActionPerformed
        // TODO add your handling code here:
        new Workoutfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuExerciseActionPerformed

    private void btnMenuNutritionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuNutritionActionPerformed
        // TODO add your handling code here:
        new NutritionMainfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuNutritionActionPerformed

    private void btnMenuProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProfileActionPerformed
        // TODO add your handling code here:
        new Profilefrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homefrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuExercise;
    private javax.swing.JButton btnMenuHome;
    private javax.swing.JButton btnMenuNutrition;
    private javax.swing.JButton btnMenuProfile;
    private javax.swing.JButton btnMenuSleep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCalories;
    private javax.swing.JLabel lblSleep;
    private javax.swing.JLabel txtWelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
