/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.GUI;

import DAO.UserDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import project.UserDetails.User;

/**
 *
 * @author perfect solution
 */
public class Profilefrm extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form Profile
     */
    public Profilefrm() {
        initComponents();
    }
    
    public Profilefrm(User user) {
        initComponents();
        this.user = user;
        lblName.setText(user.getName());
        lblEmail.setText(user.getEmail());
        lblMobileNumber.setText(user.getMobileNumber());
        lblGender.setText(user.getGender());
        lblHeight.setText(""+user.getHeight()+"cms");
        lblWeight.setText(""+user.getWeight()+"kg");
        lblAge.setText(""+user.getAge());
        if (user.isPremium())
        {
            lblAccountType.setText("Premium");
            //lblAccountType.set);
        }
        else
        {
            lblAccountType.setText("Regular");
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnMenuNutrition = new javax.swing.JButton();
        btnMenuExercise = new javax.swing.JButton();
        btnMenuHome = new javax.swing.JButton();
        btnMenuSleep = new javax.swing.JButton();
        btnMenuProfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblMobileNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        btnUpdateData = new javax.swing.JButton();
        lblAccountType = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jButton1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenuNutrition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-vegetarian-food-24.png"))); // NOI18N
        btnMenuNutrition.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuNutrition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuNutritionActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuNutrition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 90, 70));

        btnMenuExercise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exercise-24.png"))); // NOI18N
        btnMenuExercise.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuExerciseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuExercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 90, 70));

        btnMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-page-32.png"))); // NOI18N
        btnMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 90, 70));

        btnMenuSleep.setIcon(new javax.swing.ImageIcon("C:\\Users\\perfect solution\\Documents\\NetBeansProjects\\HealthFitness\\src\\main\\resources\\icons\\icons8-occupied-bed-24.png")); // NOI18N
        btnMenuSleep.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSleepActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuSleep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 90, 70));

        btnMenuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-male-user-24.png"))); // NOI18N
        btnMenuProfile.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(btnMenuProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 90, 80));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnLogout, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.btnLogout.text")); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 686, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 146, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel2.text")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 28, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel3.text")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 378, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel4.text")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel5.text")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 262, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel6.text")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 496, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel9.text")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel11.text")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 206, -1, -1));

        lblWeight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblWeight, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblWeight.text")); // NOI18N
        jPanel1.add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 496, -1, -1));

        lblHeight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblHeight, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblHeight.text")); // NOI18N
        jPanel1.add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblAge, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblAge.text")); // NOI18N
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 378, -1, -1));

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblGender, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblGender.text")); // NOI18N
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        lblMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblMobileNumber, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblMobileNumber.text")); // NOI18N
        jPanel1.add(lblMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 262, -1, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblEmail, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblEmail.text")); // NOI18N
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 206, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblName, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblName.text")); // NOI18N
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 146, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel7.text")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 564, -1, -1));

        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnChangePassword, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.btnChangePassword.text")); // NOI18N
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 626, -1, -1));

        btnUpdateData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnUpdateData, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.btnUpdateData.text")); // NOI18N
        btnUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDataActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 626, -1, -1));

        lblAccountType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAccountType.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblAccountType, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.lblAccountType.text")); // NOI18N
        jPanel1.add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 564, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(Profilefrm.class, "Profilefrm.jLabel8.text")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-510, 0, 940, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuNutritionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuNutritionActionPerformed
        // TODO add your handling code here:
        new NutritionMainfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuNutritionActionPerformed

    private void btnMenuExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuExerciseActionPerformed
        // TODO add your handling code here:
        new Workoutfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuExerciseActionPerformed

    private void btnMenuSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSleepActionPerformed
        // TODO add your handling code here:
        new Sleepfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuSleepActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Welcomefrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        JPasswordField oldPass = new JPasswordField();
        JPasswordField newPass=new JPasswordField();
        Object[] message = {
            "Enter Old Password:", oldPass,
            "Enter New Password:", newPass
        };
        JOptionPane.showInputDialog(null, message, "Change Password", JOptionPane.QUESTION_MESSAGE);
        
        if (oldPass.getText().equals(user.getPassword()))
        {
            if(!newPass.getText().equals(""))
            {
                user.setPassword(newPass.getText());
                UserDAO.updatePassword(user, newPass.getText());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Empty Password Field");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Incorrect Old Password");
        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDataActionPerformed
        // TODO add your handling code here:
        new Updateprofilefrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnUpdateDataActionPerformed

    private void btnMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuHomeActionPerformed
        // TODO add your handling code here:
        new Homefrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profilefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profilefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profilefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profilefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profilefrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuExercise;
    private javax.swing.JButton btnMenuHome;
    private javax.swing.JButton btnMenuNutrition;
    private javax.swing.JButton btnMenuProfile;
    private javax.swing.JButton btnMenuSleep;
    private javax.swing.JButton btnUpdateData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables
}
