/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.GUI;

import project.UserDetails.User;

/**
 *
 * @author perfect solution
 */
public class Workoutfrm extends javax.swing.JFrame {
    User user;
    /**
     * Creates new form Workoutfrm
     */
    public Workoutfrm(User user) {
        initComponents();
        this.user=user;
        lblHeight.setText("Height: "+user.getHeight()+ " cm");
        lblWeight.setText("Weight: "+user.getWeight()+ " kg");
    }
    
    
    public Workoutfrm() {
        initComponents();
        lblHeight.setText("Height: "+user.getHeight()+ " cm");
        lblWeight.setText("Weight: "+user.getWeight()+ " kg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnExercises = new javax.swing.JButton();
        lblWeight = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        btnMenuProfile = new javax.swing.JButton();
        btnMenuSleep = new javax.swing.JButton();
        btnMenuHome = new javax.swing.JButton();
        btnMenuExercise = new javax.swing.JButton();
        btnMenuNutrition = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Stats:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButton1.setText("Workout Routine");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 290, 90));

        btnExercises.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnExercises.setText("Exercises");
        btnExercises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExercisesActionPerformed(evt);
            }
        });
        getContentPane().add(btnExercises, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 290, 100));

        lblWeight.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(153, 153, 153));
        lblWeight.setText("Weight");
        getContentPane().add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblHeight.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(153, 153, 153));
        lblHeight.setText("Height");
        getContentPane().add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        btnMenuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-male-user-24.png"))); // NOI18N
        btnMenuProfile.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 90, 70));

        btnMenuSleep.setIcon(new javax.swing.ImageIcon("C:\\Users\\perfect solution\\Documents\\NetBeansProjects\\HealthFitness\\src\\main\\resources\\icons\\icons8-occupied-bed-24.png")); // NOI18N
        btnMenuSleep.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSleepActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuSleep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 90, 70));

        btnMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-page-32.png"))); // NOI18N
        btnMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 90, 70));

        btnMenuExercise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exercise-24.png"))); // NOI18N
        btnMenuExercise.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuExerciseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuExercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 90, 80));

        btnMenuNutrition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-vegetarian-food-24.png"))); // NOI18N
        btnMenuNutrition.setPreferredSize(new java.awt.Dimension(100, 25));
        btnMenuNutrition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuNutritionActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuNutrition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 90, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Workout");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/GUI/gym1.2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExercisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExercisesActionPerformed
        // TODO add your handling code here:
        new Exercisesfrm(user).setVisible(true);
        
        
    }//GEN-LAST:event_btnExercisesActionPerformed

    private void btnMenuSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSleepActionPerformed
        // TODO add your handling code here:
        new Sleepfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuSleepActionPerformed

    private void btnMenuExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuExerciseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMenuExerciseActionPerformed

    private void btnMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuHomeActionPerformed
        // TODO add your handling code here:
        new Homefrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Routinefrm(user).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMenuNutritionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuNutritionActionPerformed
        // TODO add your handling code here:
        new NutritionMainfrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuNutritionActionPerformed

    private void btnMenuProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProfileActionPerformed
        // TODO add your handling code here:
        new Profilefrm(user).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMenuProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workoutfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workoutfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workoutfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workoutfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workoutfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExercises;
    private javax.swing.JButton btnMenuExercise;
    private javax.swing.JButton btnMenuHome;
    private javax.swing.JButton btnMenuNutrition;
    private javax.swing.JButton btnMenuProfile;
    private javax.swing.JButton btnMenuSleep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables
}
